name: Build and validate docs

on:
  pull_request:
  push:
    branches:
      - main
      - release/v4.0.0

jobs:
  build-and-validate-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm run build
      - run: git diff --exit-code
      - run: npm run validate
